import type { LearningConcept } from "./types";

export const learningConcepts: LearningConcept[] = [
  {
    id: "consensus",
    order: 1,
    title: "What is Consensus?",
    summary: "Consensus lets servers agree on accepted commands even when some messages are delayed, lost, or blocked by partitions.",
    whyItMatters: "A replicated service must avoid two different committed histories.",
    explanation: [
      "Raft is about safely deciding which operations have been accepted by the cluster. Servers do not need to look identical at every instant.",
      "The important promise is that committed decisions do not contradict each other, even when nodes crash, restart, or temporarily cannot communicate.",
    ],
    keyPoints: ["Agreement is about committed decisions.", "A majority is used to make progress safely.", "Temporary differences are expected."],
    simulatorWatchFor: ["Watch when a candidate reaches a majority.", "Compare replicated, committed, and applied entries."],
    relatedScenarioIds: ["basic-leader-election"],
    paperSection: "Section 5.1 — Raft Basics",
  },
  {
    id: "replicated-state-machine",
    order: 2,
    title: "Replicated State Machine",
    summary: "Each server keeps a log; applying the same commands in the same order produces the same state.",
    whyItMatters: "The log is the durable order that keeps replicas consistent.",
    explanation: [
      "Raft replicates and commits log entries. A state machine then applies committed commands in order.",
      "Raft Explorer marks entries as applied, but it does not implement a real key-value database.",
    ],
    keyPoints: ["Same command order leads to same state.", "Raft manages the log, not application semantics.", "Only committed entries should be applied."],
    simulatorWatchFor: ["Look at each node log after a client command.", "Watch lastApplied advance after commit."],
    relatedScenarioIds: ["basic-leader-election"],
    paperSection: "Section 5.3 — Log Replication",
  },
  {
    id: "roles",
    order: 3,
    title: "Follower, Candidate, and Leader",
    summary: "Servers move between follower, candidate, and leader roles as elections and higher-term messages occur.",
    whyItMatters: "Raft channels most decisions through a leader to make the protocol easier to understand.",
    explanation: [
      "Followers receive leader messages. After an election timeout, a follower may become a candidate.",
      "Candidates request votes. A candidate that receives a majority becomes leader. A server that observes a valid higher-term leader message becomes follower.",
    ],
    keyPoints: ["Followers are passive until timeout.", "Candidates campaign for a term.", "Leaders accept client commands and replicate logs."],
    simulatorWatchFor: ["Node B timing out.", "Candidate B collecting votes.", "Old leaders stepping down after higher-term messages."],
    relatedScenarioIds: ["basic-leader-election", "leader-failure"],
    paperSection: "Section 5.2 — Leader Election",
  },
  {
    id: "terms",
    order: 4,
    title: "Terms",
    summary: "A term is a logical era stored independently by each server.",
    whyItMatters: "Terms let servers recognize stale leaders and stale votes.",
    explanation: [
      "Each server stores its own currentTerm. The cluster does not have a single shared currentTerm value.",
      "A new election increments a candidate's term. When a server receives a message with a higher term, it updates its own term and becomes follower.",
    ],
    keyPoints: ["Terms can temporarily differ across nodes.", "Higher terms supersede lower terms.", "Term updates happen through Raft messages."],
    simulatorWatchFor: ["Node B in Term 1 while Node C reaches Term 2 during a partition.", "Higher-term step down events."],
    relatedScenarioIds: ["leader-failure", "network-partition"],
    paperSection: "Section 5.1 — Raft Basics",
  },
  {
    id: "leader-election",
    order: 5,
    title: "Leader Election",
    summary: "A timed-out follower becomes candidate, votes for itself, requests votes, and becomes leader after a majority.",
    whyItMatters: "The cluster needs exactly one active decision maker per term.",
    explanation: [
      "Election begins with a follower timeout. The candidate increments currentTerm, votes for itself, and sends RequestVote RPCs.",
      "A voter grants at most one vote per term and also checks whether the candidate log is at least as up to date as its own log.",
    ],
    keyPoints: ["Five nodes require three votes.", "One vote per term prevents two winners in the same majority.", "The log up-to-date rule protects committed entries."],
    simulatorWatchFor: ["RequestVote messages.", "Vote responses.", "Candidate to Leader transition."],
    relatedScenarioIds: ["basic-leader-election", "split-vote"],
    paperSection: "Section 5.2 — Leader Election",
  },
  {
    id: "heartbeat",
    order: 6,
    title: "Heartbeat Is an Empty AppendEntries RPC",
    summary: "A heartbeat is not a separate Raft RPC; it is AppendEntries with an empty entries array.",
    whyItMatters: "The same RPC maintains leadership, resets election timers, and can carry leaderCommit.",
    explanation: [
      "Heartbeat uses AppendEntries fields: term, leaderId, prevLogIndex, prevLogTerm, entries, and leaderCommit.",
      "When entries is empty, the message can still prove leader contact and reset follower election timers.",
    ],
    keyPoints: ["Heartbeat is AppendEntries.", "entries = [] means no new log entries.", "An empty heartbeat does not delete extra follower logs."],
    simulatorWatchFor: ["Empty AppendEntries messages.", "Election timer reset events.", "Commit updates carried by empty AppendEntries."],
    relatedScenarioIds: ["basic-leader-election"],
    paperSection: "Section 5.2 — Leader Election",
    commonMistake: {
      misconception: "Heartbeat is a separate RPC.",
      correction: "Heartbeat is an AppendEntries RPC with no new log entries.",
    },
  },
  {
    id: "log-replication",
    order: 7,
    title: "Log Replication",
    summary: "The leader appends client commands locally, sends AppendEntries, and learns replication progress from responses.",
    whyItMatters: "Logs are how Raft orders client commands before they become committed decisions.",
    explanation: [
      "Each entry has an index, term, and command. AppendEntries also includes prevLogIndex and prevLogTerm so followers can verify the prefix.",
      "Followers store matching entries and reply. The leader updates nextIndex and matchIndex for each follower.",
    ],
    keyPoints: ["Index is the log position.", "Term is the leader term that created the entry.", "leaderCommit tells followers what the leader considers committed."],
    simulatorWatchFor: ["Leader appending a client command.", "Follower logs receiving the entry.", "AppendEntries responses advancing matchIndex."],
    relatedScenarioIds: ["basic-leader-election"],
    paperSection: "Section 5.3 — Log Replication",
  },
  {
    id: "commit-apply",
    order: 8,
    title: "Replicated, Committed, and Applied",
    summary: "Stored, replicated, majority replicated, committed, and applied are different states.",
    whyItMatters: "Confusing replication with commitment is one of the easiest ways to misunderstand Raft.",
    explanation: [
      "An entry can exist only on the leader, on some followers, or on a majority before it becomes committed.",
      "commitIndex marks the highest safe committed index. lastApplied marks the highest entry already applied to the state machine. lastApplied cannot exceed commitIndex.",
    ],
    keyPoints: ["Replicated is not always committed.", "Committed entries are applied in order.", "Majority uses configured cluster membership."],
    simulatorWatchFor: ["Minority replicated but uncommitted entries.", "Commit Index and Last Applied fields."],
    relatedScenarioIds: ["basic-leader-election", "network-partition"],
    paperSection: "Section 5.3 — Log Replication",
  },
  {
    id: "safety",
    order: 9,
    title: "Raft Safety Properties",
    summary: "Raft's rules protect elections, logs, leader completeness, and state-machine application.",
    whyItMatters: "Safety is why a committed command should not later be replaced by another command at the same index.",
    explanation: [
      "Raft Explorer demonstrates the intuition behind Raft safety properties, but it is not a formal verification tool.",
      "The RequestVote and AppendEntries rules work together to preserve committed log decisions.",
    ],
    keyPoints: ["Election Safety limits one leader per term.", "Log Matching protects common prefixes.", "State Machine Safety prevents different applied commands at the same index."],
    simulatorWatchFor: ["Split vote with no majority.", "Higher-term step down.", "Committed prefix preserved during log repair."],
    relatedScenarioIds: ["split-vote", "conflicting-logs"],
    paperSection: "Section 5.4 — Safety",
  },
  {
    id: "network-partition",
    order: 10,
    title: "Network Partitions",
    summary: "Partitioned nodes keep running, but messages across partition groups are dropped.",
    whyItMatters: "Raft must preserve safety when parts of the cluster cannot talk to each other.",
    explanation: [
      "A network partition is not a crash. Servers in each group continue running and can communicate inside their group.",
      "Majority is based on configured cluster membership, not reachable or currently running nodes.",
    ],
    keyPoints: ["A/B is a minority in a five-node cluster.", "C/D/E is a majority.", "Different partitions may temporarily show leaders in different terms."],
    simulatorWatchFor: ["Cross-partition dropped messages.", "Minority cannot commit.", "Majority elects a higher-term leader."],
    relatedScenarioIds: ["network-partition"],
    paperSection: "Section 5.2 — Leader Election",
  },
  {
    id: "conflicting-logs",
    order: 11,
    title: "Conflicting Logs and Reconciliation",
    summary: "A leader backs up nextIndex until prevLogIndex and prevLogTerm identify a shared prefix, then replaces an uncommitted conflicting suffix.",
    whyItMatters: "This is how Raft repairs divergent logs without deleting committed common-prefix entries.",
    explanation: [
      "The leader starts with nextIndex at one past its last log index. Rejections cause one-index-at-a-time backtracking in this teaching simulator.",
      "Once a prefix matches, the follower deletes the first conflicting uncommitted entry and everything after it, then appends the leader suffix.",
    ],
    keyPoints: ["Attempt 1 tests index 4 and rejects.", "Attempt 2 tests index 3 and rejects.", "Attempt 3 tests index 2 and succeeds."],
    simulatorWatchFor: ["AppendEntries rejection.", "nextIndex 5 to 4 to 3.", "Conflict truncation and final log convergence."],
    relatedScenarioIds: ["conflicting-logs", "network-partition"],
    paperSection: "Section 5.3 — Log Replication",
  },
];
